---
title: "plot_mcml & cluster_summary Demo"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 14, fig.height = 12)
devtools::load_all(".")
library(dplyr)
```

## Load Data

```{r load_data}
Interactions <- rio::import("/Users/mohammedsaqr/Documents/Network data/Mcdata/complicated_nw2.csv")
Nodesin <- rio::import('/Users/mohammedsaqr/Documents/Network data/Mcdata/Codemapping.xlsx') %>% rename(labels=Code)

Net <- cograph(Interactions, nodes = Nodesin)
Net$nodes$clusters <- Nodesin$groups

cat("Nodes:\n")
print(Net$nodes)
```

## Network Plot (with edge labels)

```{r plot, fig.width=14, fig.height=12}
plot_mcml(Net, "clusters",
          spacing = 18,
          shape_size = 6,
          scale = 4,
          layout_margin = 0.3,
          labels = TRUE,
          summary_edges = TRUE,
          show_labels = TRUE,
          node_size = 2,
          summary_size = 4,
          edge_width_range = c(0.1, 3),
          edge_labels = TRUE)
```

## Cluster Summary (within = "summary")

```{r cluster_summary}
cs <- cluster_summary(Net, within = "summary")
print(cs)
```

### Within-Cluster Weights (scalars)

```{r within_weights}
cat("Within-cluster weights:\n")
print(round(cs$within_weights, 3))
```

### Between-Cluster TNA

```{r between_tna}
cat("Between-cluster TNA:\n")
print(round(cs$tna, 3))

cat("\nInits:\n")
print(round(cs$inits, 3))
```
